Add TextInputFileRaw and TextOutputFileRaw
gap-system/gap pull request #4110
Opened 2020-09-04 20:51 UTC by ChrisJefferson

Add the ability to access files without compression, for packagemanager (and other users who might need this).

Needs some more tests before merging, checking if the naming / general design is reasonable / fixes the problem

2020-09-05 13:44 UTC, mtorpey commented
Thanks for doing this, Chris!  This should make problems in curlInterface/PackageManager fixable.

2020-09-16 16:45 UTC, mtorpey approved these changes
This looks great to me!  Not sure why it's failing Travis checks, but as far as I'm concerned it could be merged.

2020-09-22 13:19 UTC, fingolfin requested changes

2020-09-22 13:19 UTC, fingolfin commented on lib/streams.gd
> +##  <C>InputTextFileRaw</C> acts the same as <C>InputTextFile</>, without automatic
```suggestion
##  <C>InputTextFileRaw</C> acts the same as <C>InputTextFile</C>, without automatic
```

2020-09-22 13:19 UTC, fingolfin commented on lib/streams.gd
> +##  uncompression.
```suggestion
##  decompression.
```

2020-09-22 13:19 UTC, fingolfin commented on src/sysfiles.h
> +Int SyFopen(const Char * name, const Char * mode, BOOL transcompress);
What does `transcompress` stand for? I would never guess what it does based on this name. Can you please also document it in the documentation comment above this function prototype?

2020-10-07 12:38 UTC, fingolfin commented
@ChrisJefferson ping? you might want to at least merge the fixes I suggested?

2020-10-08 15:36 UTC, ChrisJefferson commented
Fixes applied, will be continued in #4128 , as I put this in gap-system/gap by accident.

2020-10-08 15:36 UTC, closed without merging