support a new command line option `systemfile`
gap-system/gap pull request #4160
Opened 2020-10-30 11:18 UTC by ThomasBreuer

... which allows one to read a given file during GAP's initialization,
after the file `lib/system.g` has been read.

The idea is that at this point, the command line options have been
evaluated, and it is a suitable place for customizing the GAP session
beyond command line options.
The motivation for this proposal is oscar-system/GAP.jl/issues/518,
see the discussion there for the background.

P.S.:
Each of the files `lib/system.g` and `src/system.c` claims that the
command line options listed there must be kept in sync with those listed
in the other file.
Apparently they are aleady out of sync.
If the claims are still relevant then of course
the new command line option should be mentioned also in `src/system.c`.

2020-10-30 11:23 UTC, ChrisJefferson commented
If this is useful to Julia, I'm generally in favour of it.

My only thought is I would either delete the "IsReadableFile" check, or at least put in an error message if the file isn't readable, else at the moment GAP will silently continue if you mispell the filename (which is probably not what we want).

2020-10-30 16:53 UTC, fingolfin commented on lib/system.g
> +  READ( GAPInfo.CommandLineOptions.systemfile );
```suggestion
if GAPInfo.CommandLineOptions.systemfile <> "" and not READ( GAPInfo.CommandLineOptions.systemfile ) then
    Error( "file \"", name, "\" must exist and be readable" );
```

In view of what @ChrisJefferson suggested (and I agree), how about doing something like the above?

2020-10-30 16:59 UTC, fingolfin reviewed
Thanks! I left a suggestion for a minor improvement.

Regarding the "keep in sync", I think one has to read these two kernel comments together:
```
/* These are just the options that need kernel processing. Additional options will be 
   recognised and handled in the library */

/* These options must be kept in sync with those in system.g, so the help output
   is correct */
```

So I think that the list in the kernel simply ought to be a subset of the list in the library (unless some command line option is intended to be kept "secret").

2020-11-04 14:01 UTC, ChrisJefferson approved these changes

2020-11-04 15:52 UTC, fingolfin requested changes
OK, `Error` doesn't work here, but let's still print to errout and set an exit code.

2020-11-04 15:52 UTC, fingolfin commented on lib/system.g
> +  QuitGap();
```suggestion
  QuitGap(1);
```
... so that we can detect from scripts that there was an error.

2020-11-04 15:52 UTC, fingolfin commented on lib/system.g
> +  Print( "Could not read file \"", GAPInfo.CommandLineOptions.systemfile,
```suggestion
  PRINT_TO( "*errout*", "Could not read file \"", GAPInfo.CommandLineOptions.systemfile,
```

2020-11-04 23:04 UTC, fingolfin approved these changes

2020-11-04 23:04 UTC, merged

2020-11-04 23:07 UTC, fingolfin commented
Backported to stable-4.11 in cabff6af41cf0ed4c5b460f5b274d621bb3a3476