fixed `HELP_SEARCH_ALTERNATIVES` again
gap-system/gap pull request #4230
Opened 2021-01-26 11:44 UTC by ThomasBreuer

Apparently there were two errors, and #4213 had dealt only with one of them.
Now the second one is fixed, and there are also tests for the relevant cases.

(This resolves issue #4229.)

2021-01-26 13:59 UTC, wilfwilson approved these changes
Thanks for doing this so quickly. I can confirm that the failures that I mentioned in #4229 are all fixed by this PR.

2021-01-26 17:05 UTC, wilfwilson requested changes

2021-01-26 17:05 UTC, wilfwilson commented on lib/helpbase.gi
> +    begin := Minimum( patterns[i].finish, Length(topic) )+1;
Oops, as with #4213, the same change should be made to `hpcgap/lib/helpbase.gi`, please.

2021-01-27 09:52 UTC, wilfwilson approved these changes
Thank you

2021-01-27 10:06 UTC, merged

2021-01-27 23:54 UTC, fingolfin commented
Just to check: does this need to be backported?

2021-01-28 09:50 UTC, ThomasBreuer commented
@fingolfin The only important point is that the pull requests #4213 and #4230 belong together --either both can be backported or none of them. I do not think that it is important to backport them.

2021-01-28 10:30 UTC, wilfwilson commented
Note that, on a quick check, it seems that the bug fixed by #4213 *does* exist in `stable-4.11`, while the bug fixed by this PR *does not* exist in `stable-4.11`:
```
gap> HELP_SEARCH_ALTERNATIVES( "Centralizer" );
[ "Centralise", "Centralize" ]
```
but this works correctly:
```
gap> ?Stabilize
```