Small fix for issue 5134
gap-system/gap pull request #5148
Opened 2022-10-20 13:18 UTC by danielrademacher

Solves #5134 

## Text for release notes

none

2022-10-20 21:07 UTC, fingolfin approved these changes

2022-10-20 21:08 UTC, fingolfin requested changes
Could you please add a test case, say based on the example in #5134? You could just add it to a new file in `tst/testbugfix`

2022-10-21 07:37 UTC, wucas commented
Maybe rebase so its only one commit?

2022-10-21 15:04 UTC, fingolfin commented
Thanks for rebasing (it's not strictly necessary, I can also "squash", but it is indeed a bit nicer)

2022-10-21 15:05 UTC, fingolfin approved these changes

2022-10-21 15:05 UTC, merged