deal with mutability questions
gap-system/gap pull request #5254
Opened 2022-12-07 15:38 UTC by ThomasBreuer

(This addresses issue #5231.)

I hope this proposal makes sense. Comments are welcome.

- changed the mutability definition for vector and matrix objects:
  - The `ConstructingFilter` value indicates whether mutable variants are possible at all, as follows: If the filter implies `IsCopyable` then one can create mutable variants, otherwise not.
  - In the definitions of `NewVector`, `ZeroVector`, `NewMatrix`, `ZeroMatrix`, `IdentityMatrix`, promise (fully) mutable results if and only if the filter in question implies `IsCopyable`.
  - In the definitions of `Vector` and `Matrix`, promise mutable results if and only if the filter in question implies `IsCopyable` and the vector/matrix that defines the entries is mutable.

- changed the currently available `ConstructingFilter` values such that they imply `IsCopyable`. (I assume that these filters can be found as follows:  ``` flags:= List( [ IsVectorObj, IsMatrixObj ], FLAG1_FILTER );; Filtered( FILTERS, x -> IsRepresentation( x ) and Intersection( flags, TRUES_FLAGS( WITH_IMPS_FLAGS( FLAGS_FILTER( x ) ) ) ) <> [] ); ``` )

- extended the definition of `Vector( v, w )` such that also the case of `w` in `IsPlistRep` is supported, and added a method for both arguments in `IsList and IsCyclotomicCollection` (to be used for example for objects in `IsAlgebraicElement`).

2022-12-15 08:58 UTC, wucas approved these changes

2022-12-15 09:00 UTC, fingolfin requested changes
As discussed I am overall very happy with this except for the low-level implementation details (see comment). Thomas is working on this; once resolved we can merge!

2022-12-15 09:00 UTC, fingolfin commented on lib/matobjnz.gd
> +##  (see <Ref Filt="IsPositionalObjectRep"/>) with <M>4</M> entries.
As we just discussed on gather.town, I'd prefer to either keep these implementation specifics out of the user-visible documentation, or else to at least qualify them to indicate that these are subject to change and one should not write code exploiting them but rather use official interfaces.

2022-12-16 13:11 UTC, ThomasBreuer commented
@fingolfin I have addressed your request.
(Somehow your comment did not get marked as "outdated": The lines in question are still there, but they were moved away from the block that is used for the documentation.)

2022-12-18 02:23 UTC, fingolfin approved these changes

2022-12-18 02:23 UTC, merged