MaximalSubgroupClassReps uses AtlasRep
gap-system/gap pull request #5485
Opened 2023-08-12 23:04 UTC by hulpke

2023-08-18 07:09 UTC, fingolfin approved these changes
Thank you! Looks good to me but it wouldn't hurt if @ThomasBreuer had another look, perhaps?

2023-08-18 09:19 UTC, ThomasBreuer requested changes
The idea is:
If AtlasRep provides information about the group in question then does it have SLPs for computing representatives for all classes of maximal subgroups?
In order to decide this, one can do the following.
```
info:= AtlasRepInfoRecord( name );
IsBound( info.nrMaxes ) and info.slpMaxes[1] = [ 1 .. info.nrMaxes ] and ForAll( info.slpMaxes[2], l -> 1 in l );
```
If the result is `true` then one can proceed as in the proposed code: Compute standard generators and use the SLPs directly if there is a `find` script, and compute an isomorphisms of groups and use `AtlasSubgroup` otherwise.

2023-08-18 14:50 UTC, hulpke commented on lib/grplatt.gi
> +          x->CallFuncList(ValueGlobal("AtlasProgram"),[inf.name,1,"maxes",x]));
Thank you -added

2023-08-25 08:16 UTC, fingolfin commented
@ThomasBreuer does this seem OK to you now?

2023-08-25 08:28 UTC, ThomasBreuer approved these changes
Thanks.
The code looks correct now, just two lines could be simplified.

2023-08-25 08:28 UTC, ThomasBreuer commented on lib/grplatt.gi
> +        if p<>fail and inf<>fail and IsBound(inf.nrMaxes) then
```suggestion
        if p<>fail then
```

2023-08-25 08:28 UTC, ThomasBreuer commented on lib/grplatt.gi
> +        elif inf<>fail and IsBound(inf.nrMaxes) then
```suggestion
        else
```

2023-08-25 11:03 UTC, fingolfin commented
Thank you! I applied @ThomasBreuer tweaks (after double checking), this will auto-merge once the test suite passed

2023-08-25 11:40 UTC, merged