Fix 'gap --version' to send its output to stdout and include a trailing newline
gap-system/gap pull request #5864
Opened 2024-12-07 11:47 UTC by fingolfin

Also add a trailing newline.

Apparently it was printing to `stdin` before. Even after looking at the code I completely fail to see *why* it did that. But while I'd love to get to the bottom of this, let's first get this trivial fix out of the door.

2024-12-07 19:54 UTC, fingolfin commented
OK it seems the issue is caused by our file descriptors not being initialized yet. The means the other `SyFputs` calls hidden by `#ifdef GAP_MEM_CHECK` in `src/system.c` may also have an issue and should be changed to `fputs(..., stderr)`. But I can't easily test this code, but perhaps @ChrisJefferson is willing to patch those

2024-12-09 17:15 UTC, dimpase requested changes
it looks like there are too many line breaks now:
```
$ ./gap --version
GAP 
4.14.0-22-g00e3a64
 built on 
2024-12-09 11:12:42-0600
```

2024-12-09 17:17 UTC, dimpase commented
I can confirm that `./gap --version </dev/null` no longer causes a crash.

2024-12-09 20:06 UTC, dimpase commented
```
  C       src/gasman.c => build/obj/src/gasman.c.o
src/gasman.c: In function ‘enableMemCheck’:
src/gasman.c:1143:5: error: implicit declaration of function ‘fputs’ [-Wimplicit-function-declaration]
 1143 |     fputs("# Warning: --enableMemCheck causes SEVERE slowdowns. Starting GAP may take several days!\n", stderr);
      |     ^~~~~
src/gasman.c:138:1: note: include ‘<stdio.h>’ or provide a declaration of ‘fputs’
  137 | #include <sys/mman.h>
  +++ |+#include <stdio.h>
  138 | #endif
src/gasman.c:1143:105: error: ‘stderr’ undeclared (first use in this function)
 1143 |     fputs("# Warning: --enableMemCheck causes SEVERE slowdowns. Starting GAP may take several days!\n", stderr);
      |                                                                                                         ^~~~~~
src/gasman.c:1143:105: note: ‘stderr’ is defined in header ‘<stdio.h>’; this is probably fixable by adding ‘#include <stdio.h>’
src/gasman.c:1143:105: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile.rules:426: build/obj/src/gasman.c.o] Error 1
```

2024-12-10 01:10 UTC, dimpase approved these changes
lgtm

2024-12-10 06:39 UTC, ChrisJefferson approved these changes

2024-12-10 06:39 UTC, merged

2025-01-17 09:43 UTC, fingolfin commented
Backported to `stable-4.14` in eeba5ab1b47d2c20cdaa0302b162ce7264c38f82